services:
  - type: web
    name: crm-reflex
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && reflex init"
    startCommand: "reflex run --env prod --loglevel info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
